# .project metadata for Kubescape
# Documentation: https://github.com/cncf/automation/tree/main/utilities/dot-project

# TODO: Add package_managers if distributed via registries

schema_version: "1.0.0"
slug: "kubescape"
name: "Kubescape"
description: "Kubescape is an open source security and compliance platform that scans clusters, Kubernetes manifest files (YAML files, and Helm charts), code repositories, container registries and images. It detects misconfigurations according to frameworks such as the NSA-CISA,  MITRE ATT&CK® and CIS, as well as software vulnerabilities, and calculates risk scores."
type: "project"
project_lead: "bezbran" # TODO: AUTO-DETECTED — please verify
cncf_slack_channel: "#kubescape" # TODO: AUTO-DETECTED — please verify

maturity_log:
  - phase: "incubating"
    date: "2022-12-13T00:00:00Z"
    issue: "https://github.com/cncf/sandbox/issues/202" # TODO: AUTO-DETECTED — please verify

repositories:
  - "https://github.com/kubescape/kubescape"

website: "https://kubescape.io/"

artwork: "https://landscape.cncf.io/logos/kubescape.svg"

adopters:
  path: "https://github.com/kubescape/kubescape/blob/main/ADOPTERS.md"

# TODO: Add package manager identifiers if your project is distributed via registries
# package_managers:
#   docker: "kubescape/kubescape"

social:
  twitter: "https://twitter.com/kubescape"

security:
  policy:
    path: "https://github.com/kubescape/kubescape/blob/master/SECURITY.md"
  contact:
    advisory_url: "https://github.com/kubescape/kubescape/security/advisories/new"

governance:
  contributing:
    path: "https://github.com/kubescape/kubescape/blob/master/CONTRIBUTING.md"
  code_of_conduct:
    path: "https://github.com/kubescape/kubescape/blob/master/CODE_OF_CONDUCT.md"

legal:
  license:
    path: "https://github.com/kubescape/kubescape/blob/master/LICENSE"
  identity_type:
    has_dco: true # AUTO-DETECTED — please verify
    has_cla: false # AUTO-DETECTED — please verify
    dco_url:
      path: "https://developercertificate.org/"

documentation:
  readme:
    path: "https://github.com/kubescape/kubescape/blob/main/README.md"

landscape:
  category: "Provisioning"
  subcategory: "Security & Compliance"

# CLOMonitor Score: 99/100
# Documentation: 100 | License: 100 | Best Practices: 95 | Security: 91
